# config.yaml

output_dir: Code/dataset
images_per_source: 30

saints:
  - Charbel
  - Antoine Le Grand
  - Joseph
  - Nimatulah Hardini
  - Maroun
  - Mary
  - George
  - Rafqa
  - Peter
  - Elias
